config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
    resources :users do
      member do
        get :following, :followers
        post :follow, to: 'users#follow'
        delete :unfollow, to: 'users#unfollow'
      end
    resources :events
    #do not need comments for users
  end

  resources :events do
    member do
      patch :terminate
    end
    resources :comments, shallow: true
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [ :index ]
      resources :events, only: [ :index ]
    end
  end

  root to: 'events#index'
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true, length: { in: 1..15 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  has_many :events
  has_many :comments, dependent: :destroy #, through: :events
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy

  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships

  mount_uploader :profile_photo, PhotoUploader

  include PgSearch
  pg_search_scope :user_search,
    against: [ :username, :name, :email ],
    using: {
      tsearch: { prefix: true }
    }

  # Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  def admin?
    self.admin
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.name.slice(0, 14)
      user.profile_photo = auth.info.image
      # user.username = "user" + "#{(0..9).sample}" + "#{(a..z).sample}"
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  def index
    if (params[:query][0] == "@")
      @users = policy_scope(User.user_search(params[:query]))
      @names = @users.map do |user|
        user.username
      end
    else
      @users = []
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user # event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to new_user_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [ :show, :following, :followers, :follow, :unfollow ]

  def index
    policy_scope(User)
    if params[:query].present?
      @users = User.user_search(params[:query]).order(name: :asc)
    end
    if @users
      authorize(@users)
    else
      @users = []
    end
  end

  def show
    authorize @user
    @events = @user.events.order(start_time: :desc)
    @markers = @events.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        image_url: helpers.asset_url('logomark.png')
      }
    end
  end

  def following
    authorize @user
    @following = @user.following
  end

  def followers
    authorize @user

    @followers = @user.followers
  end

  def follow
    authorize @user
    current_user.follow(@user) if !current_user.following?(@user)
  end

  def unfollow
    authorize @user
    current_user.unfollow(@user) if current_user.following?(@user)
  end

  private

  def find_user
    @user = User.find(params[:id])
  end
end

app/views/users/follow.js.erb
var followCounter = document.getElementById('followers-count');
followCounter.innerText = "<%= @user.followers.count %>"

var container = document.querySelector("[data-following='<%= @user.username %>']");
container.innerHTML = "<%= j render 'shared/unfollow', follower: @user %>";




//    let btninnerHtml = document.querySelector('#followbttn a')
//       btninnerHtml.innerHTML=("Unfollow");






// var btn = document.querySelector("[data-following='<%= @user.username %>']")
// btn.addEventListener('click', (e) => {
//     btn.innerHTML("Following√");
//     });

app/views/users/followers.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <%= link_to user_path do %>
      <button class="button-image-back button-image-back-alt"><i class="fas fa-angle-left"></i></button>
      <% end %>
      <div class="header-follow">
        <h3 class="text-center"><%= @user.username.humanize %>'s Followers</h3>
      </div>
      <% @followers.each do |f| %>

      <div class="follow-entire-box">
        <div class="photo-follow">
          <%= cl_image_tag f.profile_photo , class: "avatar" %>
          <%= link_to "#{f.username}", user_path(f)%>
        </div>
        <div class="position-fixed-button" data-following="<%=f.username%>">
          <% if current_user.following?(f) %>
          <%= render "shared/unfollow", follower: f %>
          <% else %>
          <%= render "shared/follow", following: f %>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>

app/views/users/following.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <%= link_to user_path do %>
      <button class="button-image-back button-image-back-alt"><i class="fas fa-angle-left"></i></button>
      <% end %>
      <div class="header-follow">
        <h3 class="text-center"><%= @user.username.humanize %>'s Following</h3>
      </div>
      <% @following.each do |f| %>

      <div class="follow-entire-box">
        <div class="photo-follow">
          <%= cl_image_tag f.profile_photo , class: "avatar" %>
          <%= link_to "#{f.username}", user_path(f)%>
        </div>
        <div  class="position-fixed-button" data-following="<%=f.username%>">
          <% if current_user.following?(f) %>
          <%= render "shared/unfollow", follower: f %>
        <% else %>
        <%= render "shared/follow", following: f %>
        <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= form_tag users_path, method: :get do %>
<%= text_field_tag :query,
params[:query],
class: "form-control search",
  placeholder: "Search for people to follow" %>
  <% end %>
  <% if @users.present? %>
  <h3>Users that match your search:</h3>
  <% @users.each do |user| %>
  <ul>
    <li><%= link_to "#{user.username}'s profile", user_path(user) %></li>
  </ul>
  <% end %>
  <% else %>
  <h5>No search results found</h5>
  <% end %>

app/views/users/show.html.erb
<div
id="map2"
style="width: 100%;
height: 60vh;"
data-markers="<%= @markers.to_json %>"
data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
>
<%= link_to root_path do %>
<button class="button-image-back button-image-back-alt"><i class="fas fa-angle-left"></i></button>
<% end %>

<% if current_user.id != @user.id %>
<% if current_user.following?(@user) %>
<div class="position-fixed-bottom" data-following="<%=@user.username%>" id="follow-button">
  <%= render "shared/unfollow", follower: @user %>
  </div>
  <% else %>
  <div class="position-fixed-bottom" data-following="<%=@user.username%>" id="follow-button">
<%= render "shared/follow", following: @user %>
</div>
<% end %>
<% else %>
<%= link_to "Edit", edit_user_registration_path(current_user), class: "follow-button" %>
<% end %>

</div>


<div class="container">
  <div class="user-info">
    <div class="photo-username">
      <%= cl_image_tag @user.profile_photo, height: 150, class: "avatar-show" %>
      <h1><%= @user.username %></h1>
    </div>
    <div class="followers-following">
      <div class="following">
        <p class="follow-heading"><%= link_to "Following", following_user_path(@user)%></p>
        <span id="follower-count"><%= @user.following.count %></span>
      </div>
      <div>
        <p class="follow-heading"><%= link_to "Followers", followers_user_path(@user)%></p>
        <span id="followers-count"><%= @user.followers.count %></span>
      </div>
    </div>
  </div>
  <div class="scroll-">
    <% @events.each do |event| %>
      <input type="hidden" value="<%= event.latitude %>" >
      <input type="hidden" value="<%= event.longitude %>">
      <% if event.end_time > Time.now %>
        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-12" >
            <div class="event-list">
              <h2 data-latitude="<%= event.latitude %>" data-longitude="<%= event.longitude.to_s %>" class="user-show-event-title see-last-event">
                <%= event.title.capitalize %>
                <% if policy(event).terminate? %>
              </h2>
              <div class="user-show-info">
                <small><%= link_to "End now", terminate_event_path(event.id), method: "patch", class: "text-success" %></small>
                <% end %>
                <% seconds = ( event.end_time - Time.now) %>
                <span data-end_time="<%= event.end_time %>" class="ended-time-js">
                  <%= Time.at(seconds).utc.strftime("%H:%M:%S") %>
                </span>
                <% if policy(event).destroy? %>
                  <%= link_to user_event_path(event.user_id, event.id), method: :delete do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="event-list ">
              <h2 data-latitude="<%= event.latitude %>" data-longitude="<%= event.longitude %>" class="user-show-event-title" class="see-last-event">
                <%= event.title.capitalize %>
              </h2>
              <div class="user-show-info">
                <small class="text-secondary">Ended</small>
                   <span class="ended-time" data-ended_time="<%= event.end_time %>"><%= event.end_time %></span>
                <% if policy(event).destroy? %>
                <%= link_to user_event_path(event.user_id, event.id), method: :delete do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
                <% end %>
            </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/unfollow.js.erb
var container = document.querySelector("[data-following='<%= @user.username %>']");
container.innerHTML = "<%= j render 'shared/follow', following: @user %>";


var followCounter = document.getElementById('followers-count');
followCounter.innerText = "<%= @user.followers.count %>"
// btn.addEventListener('click', (e) => {
//     if (btn.style.backgroundColor === "black") {
//         btn.style.backgroundColor = "yellow";
//       } else {
//         btn.style.backgroundColor = "black";
//       }
//     });




// let btninnerHtml = document.querySelector('#unfollowbttn a')