config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
    resources :users do
      member do
        get :following, :followers
        post :follow, to: 'users#follow'
        delete :unfollow, to: 'users#unfollow'
      end
    resources :events
    #do not need comments for users
  end

  resources :events do
    member do
      patch :terminate
    end
    resources :comments, shallow: true
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [ :index ]
      resources :events, only: [ :index ]
    end
  end

  root to: 'events#index'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>


<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_follow.html.erb
<%= link_to "Follow", follow_user_path(following), method: 'post', class: "follow-button", remote: true%>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div>
    <ul class="navbar-nav ">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.profile_photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">

            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>

            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>

  <% if user_signed_in? %>
      <%= form_tag events_path, method: :get do %>
        <%= text_field_tag :query,
        params[:query],
          placeholder: "@USER OR EVENT" %>
          <i class="fas fa-search lupa"></i>
      <% end %>

        <div class="users" style="position: absolute; top: 60px; z-index: 999; ">
          <ul class="list-group" id="api-results">

          </ul>
        </div>
  <% end %>
</div>

app/views/shared/_unfollow.html.erb
<%= link_to "Unfollow", unfollow_user_path(follower), method: 'delete', class: "follow-button" , remote: true%>